### ISSUE TITLE
set_mockup_now()/ get_mockup_now do not match actual contract now

### ISSUE THREAD

**Issue by grum-tez** [completium/completium-experiment-ts#3]
get_mockup_now() will return the date set by set_mockup_now(), but the actual _now_ value returned by the contract is always 1 second greater than the time provided to the set_mockup_now function

**Comment by rognierbenoit** [comment]
Hi @grum-tez it is now fixed and released as version `0.0.105` of `experiment-ts`. There is indeed  a setup of 1 second difference in mockup mode between `now` and last block date, and actually the `setMockupNow` is changing the last block date. So we simply fixed it by subtracting 1 second to the value passed to `setMockupNow` and +1 for `getMockupNow`.

**Comment by grum-tez** [comment]
Thanks for this - it is now fixed for me too - but where have you actually made changes to make this fix? I only see changes to the test files in the lastest commit to this repo.
