### ISSUE TITLE
`expect_to_fail` does not catch the exception in sandbox

### ISSUE THREAD

**Issue by lgaroche** [completium/completium-experiment-ts#4]
Are the completium tests on the sandbox supported? Exceptions are not caught when using `expect_to_fail` when the test is running on the flextesa sandbox. (It works only in mockup mode). 

Apparently, the sandbox returns a different error format than in mockup:

In mockup, the exception is this format:
```
{ value: '(Pair "INVALID_CONDITION" "r_value")' }
```
On the sandbox, it's a text exception:
```
Error: Error from contract KT1GdDuEU9CpoYGGWjyRAzTCzFyXp5TA8VdP (permits):
failed at 1692 with "INVALID_CALLER"
[...]
```

How to reproduce:
1. Clone the [FA2 template repository](https://github.com/completium/archetype-fa2)
2. Edit one of the tests, remove the `set_mockup` and `set_mockup_time` calls.
3. Start the sandbox and switch to it:
```bash
completium-cli start sandbox
completium-cli set endpoint http://localhost:20000
```
4. Run the tests: `yarn test`

**Comment by rognierbenoit** [comment]
Hi @lgaroche , indeed there was an issue with catching errors over RPC. It is now fixed.
you need to update to latest `"completium-cli"` package version in package.json `"dependencies"`: either `"latest"` or `"0.4.86"`. Then `npm i`

**Comment by lgaroche** [comment]
Hi @rognierbenoit , thanks for the update. Should there be a dependency update on the package `@completium/experiment-ts`? The is where I'm calling `expect_to_fail`

**Comment by rognierbenoit** [comment]
no because the dependency just requires a minimum version, not an exact version.

**Comment by lgaroche** [comment]
Right! I had to force update the indirect dependencies. It's working now. Thank you!

**Comment by rognierbenoit** [comment]
Can you precise the action you had to do ?

**Comment by lgaroche** [comment]
There's probably a better way, but I just deleted the node_modules folder and reinstalled.
